# Docker
- task: Docker@2
  inputs:
    containerRegistry: 'self docker'
    repository: 'test1'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: 'akshay450/$(Build.Repository.Name):$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '**/docker-compose'
        tags: |
          $(tag)
