trigger:
  branches:
    include:
    - main

pool:
  name: test1

variables:
  - group: ECR
  - name: AWS_REGION
    value: $[variables.AWS_REGION]
  - name: AWS_ACCOUNT_ID
    value: $[variables.AWS_ACCOUNT_ID]
  - name: DOCKER_REPOSITORY_NAME
    value: $[variables.DOCKER_REPOSITORY_NAME]
  - name: AWS_SECRET_ACCESS_KEY
    value: $[variables.AWS_SECRET_ACCESS_KEY]
  - name: DOCKER_REPOSITORY
    value: $[variables.DOCKER_REPOSITORY]
    #value: $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/$(DOCKER_REPOSITORY_NAME)

steps:
- bash: |
    aws ecr-public get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin public.ecr.aws/t5f9q6l8
  displayName: 'Login to AWS'
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    
- bash: echo $(AWS_ACCESS_KEY_ID)
  displayName: Env check
   
- task: Docker@2
  displayName: Build docker image
  inputs:
    repository: $(DOCKER_REPOSITORY)
    command: buildAndPush
    Dockerfile: Dockerfile
    tags: |
      $(Build.BuildId)
